// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lssbsmbjalsugejuxswa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc2JzbWJqYWxzdWdlanV4c3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjc3MjYsImV4cCI6MjA3MTcwMzcyNn0.J49SnpycVOn3oCn5Fqt0QN8MlFvuV8jM6JCMRdygyBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});